### ISSUE TITLE
Add encryption-key for packs

### ISSUE THREAD

**Issue by xxAROX** [WaterdogPE/WaterdogPE#127]
Packs will encrypt in client cache

**Comment by TobiasG-DE** [comment]
what?

**Comment by xxAROX** [comment]
Just look into "`C:\Users\<USER>\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalCache\minecraftpe\packcache\resource`" packs like hive are non human readable, because they are encrypted by mojang

**Comment by TobiasG-DE** [comment]
I am aware. But what is your proposed change? What do you want us to implement?

**Comment by xxAROX** [comment]
[That](https://github.com/pmmp/BedrockProtocol/blob/master/src/types/resourcepacks/ResourcePackInfoEntry.php#L33) is the only information that i have, but i think its not enough

**Comment by TobiasG-DE** [comment]
Are you aware that you have to have the pack already encrypted before even sending it? Also there is no good way to get the encryption key for an encrypted pack to send along the pack. And since barely anyone knows how pack encryption works, I doubt this will be of use for anyone. Whoever is able to figure out pack encryption will also know how to easily send the key.

**Comment by xxAROX** [comment]
okay
