### ISSUE TITLE
[1.18.0] Falling in the sky / Game crashing issue in Nukkit->PMMP transfers

### ISSUE THREAD

**Issue by AlicanCopur** [WaterdogPE/WaterdogPE#131]
After 1.18.0 support, when I want to transfer to PMMP from Nukkit, this warning appears in the proxy console:

`[WARN ] Received violation from AlicanCopur: PacketViolationWarningPacket(type=MALFORMED_PACKET, severity=TERMINATING_CONNECTION, packetCauseId=117, context=)`

And I'm getting "Disconnected from Server" disconnect message in Minecraft.

**Comment by Alemiz112** [comment]
It appears as one of your servers is sending CustomScriptPacket which causes player to crash.

**Comment by AlicanCopur** [comment]
Yeah, sorry about that, my fault.

But, now I have more weird issue...

https://youtu.be/JaSqXXldDoE

(There is no plugin in target (PMMP) server)

**Comment by Alemiz112** [comment]
This is caused by pmmp 1.18 chunk system but nukkit still uses 1.17.40 chunk system. Since client cannot simply change between this versions once it joins game, we can not do anything about it.

However, eventually 1.18 chunk system will get implemented into nukkit. I could possible have a look into implementing it next weekend.
