### ISSUE TITLE
Why is Powernukkit Not Supported

### ISSUE THREAD

**Issue by PocketMiner92** [WaterdogPE/WaterdogPE#173]
This is only a Question

**Comment by PleaseInsertNameHere** [comment]
Using WDPE with PowerNukkit works fine.

**Comment by TobiasGrether** [comment]
I‘m going to add it to the page in a few hours, thanks for the reminder.

**Comment by VinkyV** [comment]
Still marked as not supported!

**Comment by Alemiz112** [comment]
Because we can not ensure that PowerNukkit stops sending half-broken packets, which can't be properly decoded. The game not crashing when connecting directly does not mean sent data are correct.
Therefore only supported software is that, which we are sure about its ability to support vanilla-correct bedrock protocol and that we are able to openly speak with its developers about solving compatibility problems.

**Comment by Buddelbubi** [comment]
The PowerNukkitX dev team is very cooperatively. They would help you 100% to keep compatibility.
