### ISSUE TITLE
Scaffolding climbing is buggy

### ISSUE THREAD

**Issue by Superzock3003** [WaterdogPE/WaterdogPE#48]
**Describe the bug**
If you try to climb scaffolding, you will get a breathing-air display and can climb into the air while breathing-air display is there. I use PowerNukkit (https://github.com/Superzock3003/PowerNukkit/actions/runs/558979548) and without WaterdogPE it works without problems.
**To Reproduce**
1. Place a scaffolding
2. Climb up the scaffolding

**Expected behavior**

**Screenshots**
![Minecraft 11 02 2021 20_49_32_LI](https://user-images.githubusercontent.com/67550519/107691689-0d679900-6cac-11eb-8de4-8bf042b7a20a.jpg)

**Platform (please complete the following information):**
 - OS: Linux
 - Java 11
 - master (1.0.0)

**Comment by Alemiz112** [comment]
Thanks for opening issue, will see what I can do.

**Comment by Superzock3003** [comment]
Same happens by sneaking with a shield.

**Comment by Alemiz112** [comment]
After a while, I have found the solution. However it must be implemented in downstream side.
Both scaffolding and shield flags are part of `extended flags`. This flags should be sent together with normal flags as part of `SetEntityDataPacket` because they are used to extend those normal flags. - This seems to be vanilla expected behaviour too.
