### ISSUE TITLE
Problem with executing command with an item gui 

### ISSUE THREAD

**Issue by RealXFuryus** [WaterdogPE/WaterdogPE#81]
When connected to the proxy if you use a geysermc connected java server you won’t be able to use the items in an item gui (My Example: I cannot queue in my Practice server because when the gui opens the items won’t do anything)
OLD GEYSER VERSION:
Joined the server with WaterdogPE proxy and the commands executed from the item gui worked
NEW VERSION OF GEYSER WITH THIS BUG:
Joined the server with WaterdogPE proxy and the commands executed from the item gui don’t work
Joined the server without WaterdogPE proxy and the commands from the item gui work.
 The guis stopped working since the new update to 1.16.220 version of bedrock
These are the two geyser that i’ve used (the old version with 1.16.210 that worked fine and the new one that has this bug)
https://filebin.net/l426ni7p0s66iicx
Example video with a casual premade server:
https://filebin.net/tgqbu99bgs2ugadk
Server Version and Plugins:
PaperSpigot 1.8.8 with java 1.8.0
Plugins used: StrikePractice, Geyser-Spigot
When the geyser server is the primary server that the proxy will try to connect to the items work fine.

**Comment by Alemiz112** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Different item palette, itemStack serialization](https://trello.com/c/PNGDphDV/52-different-item-palette-itemstack-serialization)

**Comment by Alemiz112** [comment]
Hello, I have already marked this issue as resolved in our TODO board bur forgot about the GH issue 😅

To clear why this happens: Geyser has implemented newer inventory system right after update to 1.16.220 version. Most of the commonly used mcbe server software (nukkit, pmmp) use the older inventory system. Because the server defines which inv. system version is used when player joins the game. This causes inventory transactions to be marked as invalid and can not be completed by client or server.

Having this said, there is not proper solution for this situation which should be implemented on proxy side and would be effective. I recommend you to stick with one server software.
